#!/usr/bin/bash
set -e

set -o allexport
source /etc/bosnov.conf
set +o allexport


TRANSACTION="post"
SNAPPER=$(snapper -c $SNAPPER_CONFIG list | grep $TRANSACTION | tail -n 1)
SNAPPER_ID=$(echo $SNAPPER | awk -F\| '{print $2}' | tr -d ' ')
DATE=$(echo $SNAPPER | awk -F\| '{print $4}')

# Make sure we only have N newest bootentries
rm $(/usr/bin/ls -t $BOOTCTL_PATH/bosnov-*.conf | /usr/bin/tail -n+$BOOTENTRIES 2> /dev/null) 2> /dev/null

cat > "$BOOTCTL_PATH/bosnov-$SNAPPER_ID.conf" <<EOL
title   $TITLE
version $DATE
linux	/vmlinuz-linux
initrd	/initramfs-linux.img
options	$OPTIONS rootflags=subvol=$SNAPPER_SUBVOL/$SNAPPER_ID/snapshot
EOL
